export { default as Button } from './atoms/Button/Button'
export { Button } from './atoms/Button/Button'
export { default as Spinner } from './atoms/Spinner/Spinner'
export { Spinner } from './atoms/Spinner/Spinner'
export { default as Container } from './atoms/Container/Container'
export { Container } from './atoms/Container/Container'
export { default as Heading } from './atoms/Heading/Heading'
export { Heading } from './atoms/Heading/Heading'